version: 2
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  deploy:
    working_directory: ~/tellme-backend
    docker:
      - image: circleci/openjdk:11-jdk-stretch

    steps:
      - checkout
      - run:
          name: Create serviceAccountKey.json
          command: openssl aes-256-cbc -d -in ./release/serviceAccountKey.json.encrypted -k $SERVICE_ACCOUNT_KEY_DECRYPTION_KEY -md md5 >> ./src/main/resources/serviceAccountKey.json
      - run:
          name: Install Heroku CLI & login
          command: |
            curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
            heroku auth:token
      - setup_remote_docker
      - run:
          name: Deploy to Heroku
          command: |
            heroku container:push --app tellme-backend web
            heroku container:release --app tellme-backend web

  build:
    working_directory: ~/tellme-backend
    docker:
      - image: circleci/openjdk:11-jdk-stretch

    steps:
      - checkout
      - run:
          name: Create serviceAccountKey.json
          command: openssl aes-256-cbc -d -in ./release/serviceAccountKey.json.encrypted -k $SERVICE_ACCOUNT_KEY_DECRYPTION_KEY -md md5 >> ./src/main/resources/serviceAccountKey.json
      - restore_cache:
          key: tellme-backend-{{ checksum "pom.xml" }}
      - run: ./mvnw dependency:go-offline
      - run: ./mvnw spotless:check
      - run: ./mvnw package
      - save_cache:
          paths:
            - ~/.m2
          key: tellme-backend-{{ checksum "pom.xml" }}