version: 2
jobs:
  build:
    working_directory: ~/tellme-backend
    docker:
      - image: circleci/openjdk:11-jdk-stretch

    steps:
      - checkout
      - run:
          name: Create serviceAccountKey.json
          command: openssl aes-256-cbc -d -in ./release/serviceAccountKey.json.encrypted -k $SERVICE_ACCOUNT_KEY_DECRYPTION_KEY -md md5 >> ./src/main/resources/serviceAccountKey.json
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
      - run:
          name: Deploy to Heroku
          command: HEROKU_API_KEY=$HEROKU_API_KEY mvn heroku:deploy